### ISSUE TITLE
Question - remedial Jetty in Java

### ISSUE THREAD

**Issue by danizen** [Norconex/jef-monitor#6]
I'm sure it is quite easy to run JEF at a base URI below /, so that it becomes more trivial to place it behind a proxy server that is adding SSL and imposing some security.   But I have to confess I've only dealt with the Jetty configuration in Apache Solr, and it will take me awhile to figure out how to build my own JEF Monitor application based on yours.   Wicket does look cool, however, from the standpoint of fixing the mess that Spring can create.

**Comment by essiembre** [comment]
And what is the question? ;-)

If you want to map a secure URL to it, I would add a reverse proxy rule in your web server (Apache, ngingx, etc.).  You can reverse proxy from a specific path to a port.  I.e.:
```
https://mydomain.com/somepathforjef/ -> http://localhost:8080/
```
